name: Run clang-format
description: Runs clang-format and checks for any changes introduced by it
inputs:
  failCondition:
    description: Controls whether failed checks also fail the workflow run
    required: false
    default: never
  workingDirectory:
    description: Working directory for checks
    required: false
    default: ${{ github.workspace }}
runs:
  using: composite
  steps:
    - name: Check Runner Operating System 🏃‍♂️
      if: runner.os == 'Windows'
      shell: bash
      run: |
        : Check Runner Operating System 🏃‍♂️
        echo "::notice::run-clang-format action requires a macOS-based or Linux-based runner."
        exit 2

    - name: Check for Changed Files ✅
      uses: ./.github/actions/check-changes
      id: checks
      with:
        checkGlob: "'*.c' '*.h' '*.cpp' '*.hpp' '*.m' '*.mm'"
        diffFilter: 'ACM'

    - name: Install Dependencies 🛍️
      if: runner.os == 'Linux' && fromJSON(steps.checks.outputs.hasChangedFiles)
      shell: bash
      run: |
        : Install Dependencies 🛍️
        echo ::group::Install Dependencies
        sudo apt-get update
        sudo apt-get install -y python3-venv zsh
        python3 -m venv .ci-format-tools
        .ci-format-tools/bin/pip install --disable-pip-version-check clang-format==19.1.1
        echo "${GITHUB_WORKSPACE}/.ci-format-tools/bin" >> $GITHUB_PATH
        echo ::endgroup::

    - name: Run clang-format 🐉
      if: fromJSON(steps.checks.outputs.hasChangedFiles)
      id: result
      shell: zsh --no-rcs --errexit --pipefail {0}
      working-directory: ${{ inputs.workingDirectory }}
      env:
        CHANGED_FILES: ${{ steps.checks.outputs.changedFiles }}
      run: |
        : Run clang-format 🐉
        if (( ${+RUNNER_DEBUG} )) setopt XTRACE

        print ::group::Run clang-format-19
        local -a changes=(${(s:,:)CHANGED_FILES//[\[\]\'\"]/})
        FORMATTER_NAME=clang zsh build-aux/.run-format.zsh --fail-${{ inputs.failCondition }} --check ${changes}
        print ::endgroup::
